package utils

// Word represents a word with its character count
type Word struct {
	Text  string
	Count int
}

// Word lists by difficulty based on character count
var easyWords = []Word{
	{"ace", 3}, {"ant", 3}, {"arm", 3}, {"ash", 3}, {"axe", 3}, {"bad", 3}, {"bag", 3}, {"bar", 3}, 
	{"bat", 3}, {"bed", 3}, {"bee", 3}, {"BMW", 3}, {"BMX", 3}, {"bow", 3}, {"box", 3}, {"boy", 3}, 
	{"bus", 3}, {"can", 3}, {"cap", 3}, {"cat", 3}, {"cow", 3}, {"cup", 3}, {"cut", 3}, {"day", 3}, 
	{"dew", 3}, {"die", 3}, {"dig", 3}, {"DNA", 3}, {"dog", 3}, {"ear", 3}, {"eat", 3}, {"eel", 3}, 
	{"egg", 3}, {"emu", 3}, {"end", 3}, {"eye", 3}, {"flu", 3}, {"fly", 3}, {"fog", 3}, {"fox", 3}, 
	{"fur", 3}, {"gas", 3}, {"gem", 3}, {"God", 3}, {"Gru", 3}, {"ham", 3}, {"hat", 3}, {"hen", 3}, 
	{"hop", 3}, {"hot", 3}, {"hug", 3}, {"hut", 3}, {"ice", 3}, {"ivy", 3}, {"jaw", 3}, {"keg", 3}, 
	{"key", 3}, {"KFC", 3}, {"lap", 3}, {"lid", 3}, {"log", 3}, {"low", 3}, {"map", 3}, {"mop", 3}, 
	{"MTV", 3}, {"mud", 3}, {"mug", 3}, {"nun", 3}, {"nut", 3}, {"oar", 3}, {"oil", 3}, {"old", 3}, 
	{"owl", 3}, {"pan", 3}, {"paw", 3}, {"pie", 3}, {"pig", 3}, {"pin", 3}, {"pot", 3}, {"pro", 3}, 
	{"pub", 3}, {"ram", 3}, {"rat", 3}, {"red", 3}, {"rib", 3}, {"rug", 3}, {"run", 3}, {"sad", 3}, 
	{"sea", 3}, {"sew", 3}, {"shy", 3}, {"sit", 3}, {"ski", 3}, {"sky", 3}, {"son", 3}, {"spy", 3}, 
	{"sun", 3}, {"tea", 3}, {"tie", 3}, {"tip", 3}, {"toe", 3}, {"toy", 3}, {"tug", 3}, {"UFO", 3}, 
	{"USB", 3}, {"wax", 3}, {"web", 3}, {"wig", 3}, {"zoo", 3},
}

var mediumWords = []Word{
	{"ABBA", 4}, {"acid", 4}, {"acne", 4}, {"afro", 4}, {"arch", 4}, {"Asia", 4}, {"atom", 4}, {"Audi", 4}, 
	{"baby", 4}, {"bait", 4}, {"bald", 4}, {"ball", 4}, {"bank", 4}, {"bark", 4}, {"barn", 4}, {"base", 4}, 
	{"beak", 4}, {"bean", 4}, {"bear", 4}, {"beef", 4}, {"beer", 4}, {"beet", 4}, {"bell", 4}, {"belt", 4}, 
	{"bill", 4}, {"bird", 4}, {"bite", 4}, {"blue", 4}, {"boar", 4}, {"boat", 4}, {"boil", 4}, {"bomb", 4}, 
	{"book", 4}, {"bowl", 4}, {"bull", 4}, {"burp", 4}, {"cage", 4}, {"cake", 4}, {"cape", 4}, {"cash", 4}, 
	{"cast", 4}, {"cave", 4}, {"cell", 4}, {"chef", 4}, {"chew", 4}, {"chin", 4}, {"clap", 4}, {"claw", 4}, 
	{"clay", 4}, {"coal", 4}, {"coat", 4}, {"coin", 4}, {"cola", 4}, {"cold", 4}, {"comb", 4}, {"cone", 4}, 
	{"copy", 4}, {"cord", 4}, {"cork", 4}, {"corn", 4}, {"crab", 4}, {"crow", 4}, {"Cuba", 4}, {"cube", 4}, 
	{"cute", 4}, {"dead", 4}, {"deaf", 4}, {"deep", 4}, {"deer", 4}, {"dent", 4}, {"derp", 4}, {"desk", 4}, 
	{"dice", 4}, {"diet", 4}, {"diva", 4}, {"dock", 4}, {"doll", 4}, {"dome", 4}, {"door", 4}, {"Dora", 4}, 
	{"dots", 4}, {"drip", 4}, {"drum", 4}, {"duck", 4}, {"duel", 4}, {"east", 4}, {"echo", 4}, {"Elmo", 4}, 
	{"Elsa", 4}, {"exam", 4}, {"face", 4}, {"fall", 4}, {"farm", 4}, {"fast", 4}, {"fern", 4}, {"Finn", 4}, 
	{"fish", 4}, {"fizz", 4}, {"flag", 4}, {"flea", 4}, {"foil", 4}, {"food", 4}, {"fork", 4}, {"fort", 4}, 
	{"frog", 4}, {"full", 4}, {"gang", 4}, {"gasp", 4}, {"gate", 4}, {"germ", 4}, {"gift", 4}, {"girl", 4}, 
	{"glow", 4}, {"glue", 4}, {"goal", 4}, {"goat", 4}, {"gold", 4}, {"golf", 4}, {"good", 4}, {"grid", 4}, 
	{"grin", 4}, {"hair", 4}, {"half", 4}, {"halo", 4}, {"hand", 4}, {"hard", 4}, {"harp", 4}, {"head", 4}, 
	{"heat", 4}, {"heel", 4}, {"hell", 4}, {"hero", 4}, {"hill", 4}, {"hive", 4}, {"hoof", 4}, {"hook", 4}, 
	{"horn", 4}, {"hose", 4}, {"Hulk", 4}, {"hurt", 4}, {"idea", 4}, {"Ikea", 4}, {"iPad", 4}, {"iron", 4}, 
	{"jail", 4}, {"JayZ", 4}, {"jazz", 4}, {"jeep", 4}, {"king", 4}, {"kiss", 4}, {"kite", 4}, {"kiwi", 4}, 
	{"knee", 4}, {"knot", 4}, {"lady", 4}, {"lake", 4}, {"lamb", 4}, {"lamp", 4}, {"lane", 4}, {"lava", 4}, 
	{"leaf", 4}, {"leak", 4}, {"Lego", 4}, {"legs", 4}, {"lens", 4}, {"lily", 4}, {"lime", 4}, {"line", 4}, 
	{"link", 4}, {"lion", 4}, {"lips", 4}, {"loaf", 4}, {"lock", 4}, {"logo", 4}, {"loot", 4}, {"love", 4}, 
	{"luck", 4}, {"lung", 4}, {"lynx", 4}, {"maid", 4}, {"mall", 4}, {"Mars", 4}, {"mask", 4}, {"maze", 4}, 
	{"meal", 4}, {"meat", 4}, {"melt", 4}, {"meme", 4}, {"milk", 4}, {"mime", 4}, {"mint", 4}, {"mold", 4}, 
	{"mole", 4}, {"monk", 4}, {"moon", 4}, {"moss", 4}, {"moth", 4}, {"nail", 4}, {"Nasa", 4}, {"navy", 4}, 
	{"neck", 4}, {"Nemo", 4}, {"nerd", 4}, {"nest", 4}, {"Nike", 4}, {"noob", 4}, {"nose", 4}, {"nuke", 4}, 
	{"Olaf", 4}, {"open", 4}, {"orca", 4}, {"Oreo", 4}, {"oval", 4}, {"page", 4}, {"pain", 4}, {"palm", 4}, 
	{"park", 4}, {"path", 4}, {"pear", 4}, {"peas", 4}, {"pike", 4}, {"pill", 4}, {"pine", 4}, {"pink", 4}, 
	{"pipe", 4}, {"plow", 4}, {"plug", 4}, {"poke", 4}, {"polo", 4}, {"pond", 4}, {"pony", 4}, {"poop", 4}, 
	{"poor", 4}, {"pope", 4}, {"pray", 4}, {"puma", 4}, {"punk", 4}, {"race", 4}, {"raft", 4}, {"rail", 4}, 
	{"rain", 4}, {"rake", 4}, {"ramp", 4}, {"read", 4}, {"rest", 4}, {"rice", 4}, {"Rick", 4}, {"ring", 4}, 
	{"risk", 4}, {"rock", 4}, {"roll", 4}, {"Rome", 4}, {"roof", 4}, {"room", 4}, {"root", 4}, {"rose", 4}, 
	{"ruby", 4}, {"rune", 4}, {"safe", 4}, {"sale", 4}, {"salt", 4}, {"sand", 4}, {"scar", 4}, {"seal", 4}, 
	{"seed", 4}, {"shoe", 4}, {"shop", 4}, {"sick", 4}, {"silo", 4}, {"sing", 4}, {"sink", 4}, {"skin", 4}, 
	{"slam", 4}, {"slow", 4}, {"snow", 4}, {"soap", 4}, {"soda", 4}, {"soil", 4}, {"soup", 4}, {"spin", 4}, 
	{"spit", 4}, {"stab", 4}, {"star", 4}, {"step", 4}, {"swag", 4}, {"swan", 4}, {"taco", 4}, {"tail", 4}, 
	{"tank", 4}, {"tape", 4}, {"taxi", 4}, {"tear", 4}, {"tent", 4}, {"text", 4}, {"thin", 4}, {"Thor", 4}, 
	{"thug", 4}, {"tiny", 4}, {"tire", 4}, {"toad", 4}, {"tomb", 4}, {"trap", 4}, {"tree", 4}, {"tuba", 4}, 
	{"tuna", 4}, {"turd", 4}, {"twig", 4}, {"type", 4}, {"undo", 4}, {"vein", 4}, {"vent", 4}, {"vine", 4}, 
	{"vise", 4}, {"vote", 4}, {"walk", 4}, {"wall", 4}, {"warm", 4}, {"wart", 4}, {"wasp", 4}, {"wave", 4}, 
	{"weak", 4}, {"well", 4}, {"west", 4}, {"wife", 4}, {"wind", 4}, {"wine", 4}, {"wing", 4}, {"wire", 4}, 
	{"wolf", 4}, {"wool", 4}, {"work", 4}, {"worm", 4}, {"Xbox", 4}, {"yawn", 4}, {"yeti", 4}, {"Yoda", 4}, 
	{"yolk", 4}, {"Zeus", 4}, {"zoom", 4}, {"Zuma", 4},
}

var hardWords = []Word{
	{"abyss", 5}, {"AC/DC", 5}, {"acorn", 5}, {"actor", 5}, {"adult", 5}, {"alarm", 5}, {"alien", 5}, 
	{"alley", 5}, {"angel", 5}, {"angry", 5}, {"anime", 5}, {"anvil", 5}, {"Apple", 5}, {"armor", 5}, 
	{"arrow", 5}, {"attic", 5}, {"bacon", 5}, {"bagel", 5}, {"Bambi", 5}, {"banjo", 5}, {"beach", 5}, 
	{"belly", 5}, {"below", 5}, {"bench", 5}, {"Bible", 5}, {"bingo", 5}, {"birch", 5}, {"black", 5}, 
	{"blimp", 5}, {"blind", 5}, {"blood", 5}, {"blush", 5}, {"board", 5}, {"boots", 5}, {"brain", 5}, 
	{"brand", 5}, {"bread", 5}, {"brick", 5}, {"bride", 5}, {"broom", 5}, {"brush", 5}, {"bulge", 5}, 
	{"bunny", 5}, {"cabin", 5}, {"camel", 5}, {"cello", 5}, {"chain", 5}, {"chair", 5}, {"chalk", 5}, 
	{"cheek", 5}, {"chess", 5}, {"chest", 5}, {"child", 5}, {"chime", 5}, {"China", 5}, {"clean", 5}, 
	{"cliff", 5}, {"climb", 5}, {"cloak", 5}, {"clock", 5}, {"cloth", 5}, {"cloud", 5}, {"clown", 5}, 
	{"coach", 5}, {"coast", 5}, {"cobra", 5}, {"comet", 5}, {"coral", 5}, {"crack", 5}, {"crate", 5}, 
	{"cream", 5}, {"crust", 5}, {"Cupid", 5}, {"curry", 5}, {"daisy", 5}, {"dance", 5}, {"darts", 5}, 
	{"demon", 5}, {"dirty", 5}, {"dizzy", 5}, {"dough", 5}, {"drain", 5}, {"drama", 5}, {"dream", 5}, 
	{"dress", 5}, {"drink", 5}, {"drive", 5}, {"drool", 5}, {"Dumbo", 5}, {"dwarf", 5}, {"eagle", 5}, 
	{"Earth", 5}, {"Egypt", 5}, {"elbow", 5}, {"elder", 5}, {"emoji", 5}, {"error", 5}, {"fairy", 5}, 
	{"Fanta", 5}, {"fence", 5}, {"field", 5}, {"Flash", 5}, {"flask", 5}, {"flock", 5}, {"fluid", 5}, 
	{"flush", 5}, {"flute", 5}, {"frame", 5}, {"fries", 5}, {"frown", 5}, {"fruit", 5}, {"funny", 5}, 
	{"genie", 5}, {"ghost", 5}, {"giant", 5}, {"glass", 5}, {"globe", 5}, {"gloss", 5}, {"glove", 5}, 
	{"gnome", 5}, {"Goofy", 5}, {"goose", 5}, {"graph", 5}, {"grass", 5}, {"grave", 5}, {"greed", 5}, 
	{"grill", 5}, {"groom", 5}, {"gummy", 5}, {"hairy", 5}, {"happy", 5}, {"heart", 5}, {"heist", 5}, 
	{"hippo", 5}, {"honey", 5}, {"horse", 5}, {"hotel", 5}, {"house", 5}, {"hyena", 5}, {"India", 5}, 
	{"Intel", 5}, {"Italy", 5}, {"Japan", 5}, {"jeans", 5}, {"jello", 5}, {"jelly", 5}, {"Jenga", 5}, 
	{"joker", 5}, {"judge", 5}, {"juice", 5}, {"kazoo", 5}, {"kebab", 5}, {"Kirby", 5}, {"kneel", 5}, 
	{"knife", 5}, {"koala", 5}, {"label", 5}, {"laser", 5}, {"lasso", 5}, {"leash", 5}, {"leave", 5}, 
	{"leech", 5}, {"lemon", 5}, {"lemur", 5}, {"limbo", 5}, {"llama", 5}, {"loser", 5}, {"Luigi", 5}, 
	{"macho", 5}, {"mafia", 5}, {"magic", 5}, {"magma", 5}, {"Mario", 5}, {"match", 5}, {"mayor", 5}, 
	{"melon", 5}, {"messy", 5}, {"metal", 5}, {"miner", 5}, {"model", 5}, {"money", 5}, {"moose", 5}, 
	{"Morty", 5}, {"mouse", 5}, {"mouth", 5}, {"movie", 5}, {"Mummy", 5}, {"night", 5}, {"ninja", 5}, 
	{"north", 5}, {"Notch", 5}, {"novel", 5}, {"nurse", 5}, {"ocean", 5}, {"onion", 5}, {"opera", 5}, 
	{"orbit", 5}, {"organ", 5}, {"otter", 5}, {"paint", 5}, {"panda", 5}, {"pants", 5}, {"paper", 5}, 
	{"Paris", 5}, {"party", 5}, {"pasta", 5}, {"patio", 5}, {"pause", 5}, {"peace", 5}, {"peach", 5}, 
	{"pedal", 5}, {"penny", 5}, {"Pepsi", 5}, {"petal", 5}, {"piano", 5}, {"pilot", 5}, {"pinky", 5}, 
	{"pizza", 5}, {"plank", 5}, {"plate", 5}, {"Pluto", 5}, {"point", 5}, {"poppy", 5}, {"porch", 5}, 
	{"pound", 5}, {"prawn", 5}, {"prism", 5}, {"prune", 5}, {"Pumba", 5}, {"purse", 5}, {"queen", 5}, 
	{"queue", 5}, {"quill", 5}, {"quilt", 5}, {"radar", 5}, {"radio", 5}, {"razor", 5}, {"reeds", 5}, 
	{"river", 5}, {"robin", 5}, {"robot", 5}, {"royal", 5}, {"ruler", 5}, {"salad", 5}, {"Santa", 5}, 
	{"sauce", 5}, {"sauna", 5}, {"scarf", 5}, {"scary", 5}, {"scent", 5}, {"scoop", 5}, {"score", 5}, 
	{"screw", 5}, {"scuba", 5}, {"shake", 5}, {"shape", 5}, {"shark", 5}, {"sheep", 5}, {"shelf", 5}, 
	{"shell", 5}, {"shirt", 5}, {"shock", 5}, {"short", 5}, {"shout", 5}, {"Shrek", 5}, {"shrew", 5}, 
	{"shrub", 5}, {"skull", 5}, {"skunk", 5}, {"Skype", 5}, {"sleep", 5}, {"slide", 5}, {"slime", 5}, 
	{"slope", 5}, {"sloth", 5}, {"slump", 5}, {"smell", 5}, {"smile", 5}, {"smoke", 5}, {"snail", 5}, 
	{"snake", 5}, {"socks", 5}, {"Sonic", 5}, {"sound", 5}, {"south", 5}, {"space", 5}, {"spade", 5}, 
	{"Spain", 5}, {"spark", 5}, {"spear", 5}, {"spine", 5}, {"spool", 5}, {"spoon", 5}, {"spore", 5}, 
	{"squid", 5}, {"stage", 5}, {"stamp", 5}, {"stand", 5}, {"Steam", 5}, {"sting", 5}, {"stone", 5}, 
	{"stork", 5}, {"storm", 5}, {"stove", 5}, {"straw", 5}, {"study", 5}, {"sugar", 5}, {"sushi", 5}, 
	{"swamp", 5}, {"swarm", 5}, {"sweat", 5}, {"swing", 5}, {"sword", 5}, {"table", 5}, {"Tails", 5}, 
	{"taser", 5}, {"thief", 5}, {"think", 5}, {"thumb", 5}, {"tiger", 5}, {"tired", 5}, {"toast", 5}, 
	{"tooth", 5}, {"torch", 5}, {"totem", 5}, {"touch", 5}, {"towel", 5}, {"tower", 5}, {"train", 5}, 
	{"trend", 5}, {"T-rex", 5}, {"truck", 5}, {"tumor", 5}, {"udder", 5}, {"uncle", 5}, {"vault", 5}, 
	{"Venus", 5}, {"video", 5}, {"viola", 5}, {"virus", 5}, {"vodka", 5}, {"vomit", 5}, {"waist", 5}, 
	{"watch", 5}, {"water", 5}, {"whale", 5}, {"wheel", 5}, {"whisk", 5}, {"white", 5}, {"witch", 5}, 
	{"W-LAN", 5}, {"world", 5}, {"wound", 5}, {"wrist", 5}, {"Xerox", 5}, {"x-ray", 5}, {"yacht", 5}, 
	{"Yoshi", 5}, {"young", 5}, {"yo-yo", 5}, {"zebra", 5}, {"Zelda", 5}, {"Zorro", 5},
}